#!/usr/bin/env bash

create_users() {
    while read line; do
        if [ ! -z "${line}" ]; then
            user_to_create=""
            # username;shell;root;pubkey
            IFS=";" user_to_create=( $line )

            [ -z "${user_to_create[1]}" ] && user_shell="/bin/bash" || user_shell="$(which "${user_to_create[1]}")"
            username="${user_to_create[0]}"
            user_is_root="${user_to_create[2]}"
            user_pubkey="${user_to_create[3]}"

            echo "\n==============================="
            echo "$usernme:"
            echo "\tsudoers: $user_is_root"
            echo "\tshell: $user_shell"
            echo "\tpubkey: $user_pubkey"
            echo ""

            # -U: create a group with same name as username
            # -m: create home dir
            # -d: specify home dir
            echo "useradd -U -m -d /home/${username} -s ${user_shell} ${username}"
            useradd -U -m -d /home/${username} -s "${user_shell}" "${username}"

            if [ "${user_is_root}" -eq "1" ]; then
                echo "Add user ${user_pubkey} to suders"
                echo "${username} ALL:ALL" >> /etc/sudoers
            fi

            if [ ! -z "${user_pubkey}" ]; then
                echo "mkdir /home/${username}/.ssh"
                mkdir "/home/${username}/.ssh"
                echo "${user_pubkey}" >> "/home/${username}/.ssh/authorized_keys"

                echo "chown -R ${username}:${username} /home/${username}/.ssh"
                chown -R ${username}:${username} /home/${username}/.ssh
                echo "chmod 700 /home/${username}/.ssh/authorized_keys"
                chmod 700 "/home/${username}/.ssh/authorized_keys"
            fi
            echo "===============================\n"
        fi
    done <(wget --no-check-certificate -O - "${URI_ROOT}resources/user_list")
}

ssh_config() {
    sed -i 's/#\? *\(PermitRootLogin\)\ yes/\1\ no/g' /etc/ssh/sshd_config
    sed -i 's/#\? *\(ChallengeResponseAuthentication\)\ yes/\1\ no/g' /etc/ssh/sshd_config
    sed -i 's/#\? *\(PasswordAuthentication\)\ yes/\1\ no/g' /etc/ssh/sshd_config
    sed -i 's/#\? *\(PubkeyAuthentication\)\ no/\1\ yes/g' /etc/ssh/sshd_config

    service ssh restart
}

main() {
    create_users
    ssh_config
}

main
